modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="my_mod"
version="1.0.0"
displayName="my mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Luis64_gamer, MCreator"

[[dependencies.my_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



